[package]
name = "anda_cli"
description = "The command line interface for Anda engine server."
repository = "https://github.com/ldclabs/anda/tree/main/anda_cli"
publish = true
version = "0.7.0"
edition.workspace = true
keywords.workspace = true
categories.workspace = true
license.workspace = true

[dependencies]
anda_core = { path = "../anda_core", version = "0.7" }
anda_web3_client = { path = "../anda_web3_client", version = "0.7" }
base64 = { workspace = true }
clap = { workspace = true }
dotenv = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
hex = { workspace = true }
rand = { workspace = true }
ciborium = { workspace = true }

[dev-dependencies]
